name    'silpion-solutionscamphacks'
version '0.1.0'
source 'UNKNOWN'
author 'Mark Kusch <mark.kusch@silpion.de>'
license 'Apache License, Version 2.0'
summary 'Hacks to support the Solutionscamp Docker space'
description 'Hacks to support the Solutionscamp Docker space'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
